apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: cb-kubecd
    provider: github
    repository: dwjw01
  name: cb-kubecd-dwjw01
spec:
  description: Imported application for cb-kubecd/dwjw01
  httpCloneURL: https://github.com/cb-kubecd/dwjw01.git
  org: cb-kubecd
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: dwjw01
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/cb-kubecd/dwjw01.git
